import { BALANCE_DISTRIBUTION_SETTING, WAITING_TIME_IN_HOURS } from './enums'

export const PAGINATION_LIMIT = 10

export const SELECT_DEFAULT_VALUE = '-1'

export const WAITING_TIME_IN_HOURS_DEFAULT_VALUE = WAITING_TIME_IN_HOURS.UM_DIA

export const BALANCE_DISTRIBUTION_SETTING_DEFAULT_VALUE = BALANCE_DISTRIBUTION_SETTING.NAO_DISTRIBUIR_ENTRE_VOUCHERS
